package framework.seed.verification

import chisel3._
import chisel3.util._
import framework.seed.configs.SeedParam
import framework.seed.pipeline.PCReg

/** Wiring and sampling context; properties are generated by chisel-iabv. */
class PCRegVerificationTop extends Module {
  val p = SeedParam()
  val io = IO(new Bundle {
    val redirect = Flipped(Valid(UInt(p.vaddrBits.W)))
    val advance = Input(Bool())
    val pc = Output(UInt(p.vaddrBits.W))
  })
  val dut = Module(new PCReg(p))
  dut.io.redirect := io.redirect
  dut.io.advance := io.advance
  io.pc := dut.io.pc

  // Uninitialized history registers are read only by next-cycle consequents.
  val previousPc = RegNext(io.pc)
  val previousTarget = RegNext(io.redirect.bits)
  // Product injects generated Chisel LTL properties into the run workspace.

}

object EmitPCRegVerification extends App {
  _root_.circt.stage.ChiselStage.emitSystemVerilogFile(
    new PCRegVerificationTop,
    Array("--target-dir", "build/pc-reg-rtl"),
    Array("--disable-all-randomization")
  )
}
